name: Wijzigingsformulier
description: Stel een (inhoudelijke) wijziging voor op de Digikoppeling standaard. Voor een tekstueele wijziging op de documentatie bestaat een ander formulier.
title: "RFC 2022 xxxx"
labels: ["digikoppeling", "wijziging"]
body:
  - type: checkboxes
    id: standaard
    attributes:
      label: Standaard
      description: Kies één van de standaarden waarop de wijziging betrekking heeft.
      options:
        - label: WUS
        - label: ebMS
        - label: API
  - type: textarea
    id: omschrijving
    attributes:
      label: Omschrijving
      description: Wat is de voorgestelde wijziging? 
      placeholder: Beschrijving van de wijziging.
      value: Vul hier de voorgestelde aanpassing in
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Naam
      description: Naam
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
      description: E-mail adres
    validations:
      required: true
