name: Wijzigingsformulier
description: Stel een wijziging voor in de Digikoppeling standaard
title: "[Wijziging]: "
labels: ["digikoppeling", "wijziging"]
body:
  - type: dropdown
    id: document
    attributes:
      label: Document
      description: Wanneer u een fout of aanpassing in een document wil voorstellen kunt u hier aangeven om welk document het gaat.
      options:
        - Wat is Digikoppeling?
        - Digikoppeling Overzicht Actuele Documentatie en Compliance
        - Beheermodel en Releasebeleid
        - Architectuur
        - Identificatie en Authenticatie
    validation:
      required: true
  - type: input
    id: contact
    attributes:
      label: Naam
      description: Naam
      validations:
        required: false
  - type: input
    id: email
    attributes:
      label: Email
      description: E-mail adres 
      validations:
        required: true
