name: Wijzigingsformulier
description: Stel een wijziging voor in de Digikoppeling standaard
title: "[Wijziging]: "
labels: ["digikoppeling", "wijziging"]
body:
  - type: dropdown
    id: document
    attributes:
      label: Document
      description: Wanneer u een fout of aanpassing in een document wil voorstellen kunt u hier aangeven om welk document het gaat.
      options:
        - Wat is Digikoppeling?
        - Digikoppeling Overzicht Actuele Documentatie en Compliance
        - Beheermodel en Releasebeleid
        - Architectuur
        - Identificatie en Authenticatie
        - Beveiliging standaarden en voorschriften
        - Koppelvlakstandaard WUS
    validations:
      required: true
  - type: checkboxes
    id: standaard
    attributes:
      label: Standaard
      description: Kies één van de standaarden waarop de wijziging betrekking heeft.
      options:
        - label: WUS
        - label: ebMS
        - label: API
  - type: textarea
    id: omschrijving
    attributes:
      label: Omschrijving
      description: Wat is de voorgestelde wijziging? Op welke pagina of sectie staat het?
      placeholder: Beschrijving van de wijziging inclusief de plaats in het document.
      value: Schreiffaut
    validations:
      required: true
  - type: checkboxes
    id: soort
    attributes:
      label: Soort wijziging
      description: Kies één of meer opties.
      options:
        - label: Tekstueel: Wijziging zonder impact op de standaard (spelfouten e.d.)
        - label: Functioneel: Wijziging met impact op de manier waarop de standaard toegepast wordt.
  - type: input
    id: contact
    attributes:
      label: Naam
      description: Naam
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
      description: E-mail adres
    validations:
      required: true
