name: Build
on:
  workflow_call:
jobs:
  main:
    name: Snapshot
    runs-on: ubuntu-22.04
    env:
      SOURCE_INPUT_FILE_NAME: ${{ env.SOURCE_INPUT_FILE_NAME || 'index.html' }}
    steps:
      - run: mkdir ~/static
      - name: Create cache
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - uses: actions/checkout@v4
      - name: Static HTML
        run: |
          npx respec --localhost --src $SOURCE_INPUT_FILE_NAME --out ~/static/snapshot.html --haltonwarn
      - name: PDF
        run: |
         cp ~/static/snapshot.html snapshot.html
         npm i puppeteer
         python3 -m http.server 8080 &
         wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/pdf.js
         rm -f *.pdf
         node pdf.js
         find *.pdf
         mv *.pdf ~/static/
