name: Check
on:
  workflow_call:
jobs:  
  wcag:
    name: WCAG
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Recover HTML
        uses: actions/cache@v3
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - run: mv ~/static/snapshot.html snapshot.html
      - run: npm install -g pa11y
      - run: pa11y snapshot.html

  links:
    name: Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Recover HTML
        uses: actions/cache@v3
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - run: mv ~/static/snapshot.html snapshot.html
      - name: Local server
        run: python3 -m http.server 8080 &
      - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Install muffet
        run: brew install muffet      
      - name: Check links      
        run: muffet --ignore-fragments --exclude '8080\/\S*\.pdf' --one-page-only http://localhost:8080/snapshot.html
