name: Check
on:
  workflow_call:
jobs:  
  wcag:
    name: WCAG
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - run: mv ~/static/snapshot.html snapshot.html
      - run: npm install @axe-core/cli browser-driver-manager -g
      - run: npx browser-driver-manager install chrome
      - name: Serve Files
        uses: Eun/http-server-action@v1
        with:
          content-types: |
            {
              "css": "text/css",
              "html": "text/html",
              "ico": "image/x-icon",
              "jpeg": "image/jpeg",
              "jpg": "image/jpeg",
              "js": "text/javascript",
              "json": "application/json",
              "png": "image/png",
              "svg": "image/svg+xml",
              "txt": "text/plain",
              "xml": "text/xml"
            }
      - run: axe http://localhost:8080/snapshot.html --exit --tags wcag2aa
  
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Download configuration
        run: wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/.markdownlint.yaml
      - name: Run linter
        if: ${{ hashFiles('sections/') != '' }}
        run: markdownlint sections/

  links:
    name: Links
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - run: mv ~/static/snapshot.html snapshot.html
      - name: Serve Files
        uses: Eun/http-server-action@v1
        with:
          content-types: |
            {
              "css": "text/css",
              "html": "text/html",
              "ico": "image/x-icon",
              "jpeg": "image/jpeg",
              "jpg": "image/jpeg",
              "js": "text/javascript",
              "json": "application/json",
              "png": "image/png",
              "svg": "image/svg+xml",
              "txt": "text/plain",
              "xml": "text/xml"
            }
      - run: echo '/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin' >> $GITHUB_PATH
      - name: Install muffet
        run: brew install muffet      
      - name: Check links
        run: |
          wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/run-muffet.sh
          bash run-muffet.sh http://localhost:8080/snapshot.html
