name: Check
on:
  workflow_call:
jobs:  
  wcag:
    name: WCAG
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - run: mv ~/static/snapshot.html snapshot.html
      - run: npm install -g pa11y
      - run: pa11y snapshot.html --ignore WCAG2AA.Principle4.Guideline4_1.4_1_1.F77

  links:
    name: Links
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - run: mv ~/static/snapshot.html snapshot.html
      - name: Local server
        run: python3 -m http.server 8080 &
      - run: echo '/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin' >> $GITHUB_PATH
      - name: Install muffet
        run: brew install muffet      
      - name: Check links      
        run: >
          muffet
          --exclude '8080\/\S*\.pdf'
          --exclude '^https:\/\/gitdocumentatie.*(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?'
          --exclude 'upwork.com'
          --exclude 'sitearchief.nl'
          --exclude 'opengis.net'
          --header 'user-agent:Curl' --ignore-fragments --one-page-only http://localhost:8080/snapshot.html
          --buffer-size 8192
