name: Check
on:
  workflow_call:
jobs:  
  wcag:
    name: WCAG
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Recover HTML
        uses: actions/cache/restore@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - run: mv ~/static/index.html index.html
      - run: npm install @axe-core/cli browser-driver-manager -g
      - run: npx browser-driver-manager install chrome
      - name: Serve Files
        uses: Eun/http-server-action@v1
        with:
          content-types: |
            {
              "css": "text/css",
              "html": "text/html",
              "ico": "image/x-icon",
              "jpeg": "image/jpeg",
              "jpg": "image/jpeg",
              "js": "text/javascript",
              "json": "application/json",
              "png": "image/png",
              "svg": "image/svg+xml",
              "txt": "text/plain",
              "xml": "text/xml"
            }
      - run: axe http://localhost:8080/index.html --exit --tags wcag2aa
  
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Install markdownlint plugins
        run: npm install markdownlint-rule-search-replace
      - name: Download configuration
        run: wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/.markdownlint.yaml
      - name: Run linter
        if: ${{ hashFiles('sections/') != '' }}
        run: markdownlint -r markdownlint-rule-search-replace sections/

  links:
    name: Links
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4
      - name: Recover HTML
        uses: actions/cache/restore@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - run: mv ~/static/*.html ~/static/*.pdf .
      - name: Serve Files
        uses: Eun/http-server-action@v1
        with:
          content-types: |
            {
              "css": "text/css",
              "html": "text/html",
              "ico": "image/x-icon",
              "jpeg": "image/jpeg",
              "jpg": "image/jpeg",
              "js": "text/javascript",
              "json": "application/json",
              "png": "image/png",
              "svg": "image/svg+xml",
              "txt": "text/plain",
              "xml": "text/xml"
            }
      - run: echo '/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin' >> $GITHUB_PATH
      - name: Install muffet
        run: |
          brew update
          brew install muffet      
      - name: Check links
        run: |
          wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/run-muffet.sh
          bash run-muffet.sh http://localhost:8080/index.html
  spellchecker:
    name: Run spellcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install hunspell
        run: |
          sudo apt-get install hunspell
          wget -O en_GB.aff https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/spellcheck/en_GB.aff
          wget -O en_GB.dic https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/spellcheck/en_GB.dic
          wget -O logius.aff https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/spellcheck/logius.aff
          wget -O logius.dic https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/spellcheck/logius.dic
      - name: Build spellcheck version of standard
        run: |
          REPLACEMENT_REGEX="s/spellcheck: false/spellcheck: true/"
          sed -i "$REPLACEMENT_REGEX" js/config.mjs
          mkdir ~/static
          npx respec --localhost --src index.html --out ~/static/index.html --haltonwarn
      - name: Run spellcheck
        if: ${{ hashFiles('standaard.dic') != '' }}
        run: |
          hunspell -l -d en_GB,logius,standaard -H ~/static/index.html | sort -u > spelling.txt
          if [ -s spelling.txt ]; then
            echo "De volgende woorden zijn niet toegestaan:"
            cat spelling.txt
            exit 1
          fi
