on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

name: Check issues
jobs:
  link-checker:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install --upgrade PyGitHub
      - run: mkdir -p issues
      - name: Issues
        env:
          SANDERKE: ${{ secrets.SANDERKE }}
        run: python ./scripts/issues.py
      - name: RFCs
        env:
          SANDERKE: ${{ secrets.SANDERKE }}
        run: python ./scripts/rfc.py
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update issues report
