name: Publish
on:
  workflow_call:
    secrets:
      BEHEER:
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.repository_owner == 'Logius-standaarden' && ( github.ref_name == 'main' || github.ref_name == 'master' || github.ref_name == 'en' ) }}
    steps:
      - uses: actions/checkout@v4
      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - name: Gather files
        run: |
         wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/gather-files.sh
         bash gather-files.sh
         git clone https://user:${{ secrets.BEHEER }}@github.com/Logius-standaarden/publicatie.git
      - name: Commit release
        run: |
         wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/release.py
         python release.py
         cd publicatie
         git add -A
         git config user.name "GitHub Action"
         git config user.email "api@logius.nl"
         git diff-index --quiet HEAD || git commit -m "Release: ${{ github.event.repository.name }}"
         git push
  upload_develop_artifacts:
    name: Upload develop artifacts
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.repository_owner == 'Logius-standaarden' && github.ref_name == 'develop' }}
    steps:
      - uses: actions/checkout@v4
      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - name: Rename index
        run: |
          wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/gather-files.sh
          bash gather-files.sh
          mkdir _site
          mv ~/content/* _site
      - name: Upload static files as artifact
        id: upload_pages_artifact
        uses: actions/upload-pages-artifact@v3
  deploy-develop:
    name: Deploy develop
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.upload_pages_artifact.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: upload_develop_artifacts
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  preview:
    name: Preview
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork && github.repository_owner == 'Logius-standaarden' && github.head_ref != 'develop' }}
    env:
      ORGANISATION_URL: https://logius-standaarden.github.io
      PREVIEW_REPOSITORY_NAME: Publicatie-Preview
      REPOSITORY_NAME_AND_BRANCH: ${{ github.event.repository.name }}/${{ github.head_ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - name: Gather files
        run: |
         wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/gather-files.sh
         bash gather-files.sh
         git clone https://user:${{ secrets.BEHEER }}@github.com/Logius-standaarden/$PREVIEW_REPOSITORY_NAME.git
      - name: Commit preview
        run: |
         cd $PREVIEW_REPOSITORY_NAME
         rm -f -r $REPOSITORY_NAME_AND_BRANCH
         mkdir -p $REPOSITORY_NAME_AND_BRANCH
         mv ~/content/* $REPOSITORY_NAME_AND_BRANCH
         git add -A
         git config user.name "GitHub Action"
         git config user.email "api@logius.nl"
         git diff-index --quiet HEAD || git commit -m "new preview build"
         git push
      - name: Zoek preview link
        uses: peter-evans/find-comment@v3
        id: findcomment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Preview link voor pull request

      - name: Post preview link
        if: steps.findcomment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        env:
          PREVIEW_LINK_URL: ${{ env.ORGANISATION_URL }}/${{ env.PREVIEW_REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME_AND_BRANCH }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            [Preview link voor pull request](${{ env.PREVIEW_LINK_URL }})
            [Diff met W3CDiff](https://services.w3.org/htmldiff?doc1=${{ env.ORGANISATION_URL }}/${{ github.event.repository.name }}&doc2=${{ env.PREVIEW_LINK_URL }})

