name: Build and Check
on:
  workflow_call:
jobs:
  main:
    name: HTML and PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: HTML
        run: npx respec --localhost --src index.html --out snapshot.html
      - name: PDF
        run: |
         if [[ $(git status --porcelain) ]]
         then echo "New snapshot.html. Generating PDF"
         else exit 0
         fi
         sudo apt-get install -y xfonts-base xfonts-75dpi
         wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb -O wkhtmltopdf.deb
         sudo dpkg -i wkhtmltopdf.deb
         rm wkhtmltopdf.deb
         wkhtmltopdf --enable-local-file-access snapshot.html doc.pdf       
         wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/pdf-name.py
         python pdf-name.py
         rm pdf-name.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: snapshot
  wcag:
    needs: main
    name: WCAG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - run: npm install -g pa11y
      - run: pa11y ./snapshot.html
  links:
    needs: main
    name: Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - run: |
         python3 -m http.server 8080 &
         brew install muffet         
         muffet --one-page-only http://localhost:8080/snapshot.html
